"""
Django settings for YYAS project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _

LANGUAGES = (
    ('en', _('English')),
    ('vi', _('Vietnamese')),
)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

AUTH_USER_MODEL = 'yyasweb.CustomUser'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7m9g^jgb(8mb7m3jh3(hv^t*)hn9#(vpr9f%gq06!51*9+g!d_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '127.0.0.1:8000', 'localhost:8000', '*',]

LOCALE_PATHS = (os.path.join(BASE_DIR, 'locale'),'locale')

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'yyasweb',
    'bootstrap3',
    "django_cron",
    "rest_framework",
    'rest_framework.authtoken',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'YYAS.urls'
PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.MD5PasswordHasher',
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'YYAS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('auction_list')
LOGOUT_REDIRECT_URL = reverse_lazy('home')
DATETIME_INPUT_FORMAT = '%Y-%m-%d %H:%M'
TIME_GAP = 3

# Sending email properties
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'tantrokiniem@gmail.com'
EMAIL_HOST_PASSWORD = 'xyhzzoddgoafbyfh'
EMAIL_PORT = 587

# Curency property
CURRENCY_FETCH_URL = 'https://openexchangerates.org/api/latest.json?app_id=0b598d5d2f014d7883905f71ab61add4'
TEMP_CURRENCY = 'currency'
BASE_CURRENCY = 'EUR'

# Email messages
BAN_HEADER = "YOUR AUCTION HAS BEEN BANNED"
BAN_BIDDER_HEADER = "THE AUCTION YOU BIDDED HAS BEEN BANNED"
BAN_CONTENT = "AUCTION : %s - has been banned"

RESOLVE_HEADER = "YOUR AUCTION HAS BEEN RESOLVED"
RESOLVE_BIDDER_HEADER = "THE AUCTION YOU BIDDED HAS BEEN RESOLVED"
RESOLVE_CONTENT = "AUCTION : has been resolved at %s"

BID_HEADER = "NEW BID PLACED"
BID_CONTENT = "Somebody just placed a new bid in your auction at %s"

DEFAULT_LANGUAGE = 'en'
LANGUAGE_CHOICES = (('en', 'English'), ('vi', 'Vietnamese'),)

ERROR_CONCURRENCY_MESSAGE = 'This auction has been changed. Please reload the page and re-submit your bid'

